
package ui;
import ez.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DiegoArboleda
 */
public class LoginView extends javax.swing.JFrame {
          
    boolean loggedIn ;
    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();       
        setSize(900, 600);
        setLocationRelativeTo(null);
    }
    
     /**
     * The showLoginView method is used to set the LoginView JFrame visible
     */
    public void showLoginView(){
        setVisible(true);
}
    
       /**
     * The hideLoginView method is used to set the LoginView JFrame NOT visible
     */
    public void hideLoginView(){
        setVisible(false);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        ezTitleLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        forgotPasswordLabel = new javax.swing.JLabel();
        backToInventoryButton = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        backgroundjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(660, 629));
        getContentPane().setLayout(null);

        usernameLabel.setBackground(new java.awt.Color(255, 255, 255));
        usernameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(0, 0, 0));
        usernameLabel.setText("User Name:");
        getContentPane().add(usernameLabel);
        usernameLabel.setBounds(330, 110, 80, 19);

        passwordLabel.setBackground(new java.awt.Color(255, 255, 255));
        passwordLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(0, 0, 0));
        passwordLabel.setText("Password:");
        passwordLabel.setToolTipText("");
        getContentPane().add(passwordLabel);
        passwordLabel.setBounds(330, 140, 72, 19);
        getContentPane().add(userNameTextField);
        userNameTextField.setBounds(440, 110, 100, 19);

        ezTitleLabel.setFont(new java.awt.Font("Mongolian Baiti", 0, 48)); // NOI18N
        ezTitleLabel.setForeground(new java.awt.Color(0, 102, 51));
        ezTitleLabel.setText("EZ Shopping");
        getContentPane().add(ezTitleLabel);
        ezTitleLabel.setBounds(300, 40, 290, 50);

        loginButton.setForeground(new java.awt.Color(0, 0, 0));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(440, 180, 100, 25);

        forgotPasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        forgotPasswordLabel.setText("Forgot Password");
        forgotPasswordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPasswordLabelMouseClicked(evt);
            }
        });
        getContentPane().add(forgotPasswordLabel);
        forgotPasswordLabel.setBounds(440, 220, 110, 15);

        backToInventoryButton.setText("Back To Inventory");
        backToInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToInventoryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backToInventoryButton);
        backToInventoryButton.setBounds(430, 460, 140, 25);
        getContentPane().add(jPasswordField);
        jPasswordField.setBounds(440, 140, 100, 19);

        backgroundjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ez/imgs/background_color.jpg"))); // NOI18N
        backgroundjLabel.setMaximumSize(new java.awt.Dimension(900, 600));
        backgroundjLabel.setMinimumSize(new java.awt.Dimension(900, 600));
        backgroundjLabel.setName(""); // NOI18N
        getContentPane().add(backgroundjLabel);
        backgroundjLabel.setBounds(0, 0, 900, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forgotPasswordLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordLabelMouseClicked
        // Code to open forgot password window
      
    }//GEN-LAST:event_forgotPasswordLabelMouseClicked

    /**
     * loginButtonActionPerformed
     *
     * @dexcription on click takes user name and password and provides them to
     * the login class for the user to login
     */
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
          
        String userN = userNameTextField.getText();
        String pwd = jPasswordField.getText();

        Logger log = Logger.getInstance();
        String loginResult = log.login(userN, pwd);
        
        if (loginResult.contains("successfully")) {
                       
            loginResult += ". You will now be redirected to the inventory.";
            JOptionPane.showMessageDialog(null, loginResult);
                       
            SystemView systemView = new SystemView();
            hideLoginView();
            loggedIn = true;            
            systemView.showSystemViewAfterLogin(loggedIn, userN);   
            
        } else {
            loggedIn = false;
            JOptionPane.showMessageDialog(null, loginResult);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void backToInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToInventoryButtonActionPerformed
            SystemView systemView = new SystemView();
            setVisible(false);
            loggedIn = false;
            systemView.showSystemView(loggedIn);
    }//GEN-LAST:event_backToInventoryButtonActionPerformed
 
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToInventoryButton;
    private javax.swing.JLabel backgroundjLabel;
    private javax.swing.JLabel ezTitleLabel;
    private javax.swing.JLabel forgotPasswordLabel;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
