
package ui;
import ez.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DiegoArboleda
 */
public class LoginView extends javax.swing.JFrame {
       private boolean loggedIn;
    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();       
    }
    
     /**
     * The showLoginView method is used to set the LoginView JFrame visible
     */
    public void showLoginView(){
     new LoginView().setVisible(true);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        ezTitleLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        forgotPasswordLabel = new javax.swing.JLabel();
        backgroundjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(660, 629));
        getContentPane().setLayout(null);

        usernameLabel.setBackground(new java.awt.Color(255, 255, 255));
        usernameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(0, 0, 0));
        usernameLabel.setText("User Name:");
        getContentPane().add(usernameLabel);
        usernameLabel.setBounds(200, 100, 80, 19);

        passwordLabel.setBackground(new java.awt.Color(255, 255, 255));
        passwordLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(0, 0, 0));
        passwordLabel.setText("Password:");
        passwordLabel.setToolTipText("");
        getContentPane().add(passwordLabel);
        passwordLabel.setBounds(200, 130, 72, 19);
        getContentPane().add(userNameTextField);
        userNameTextField.setBounds(310, 100, 100, 19);
        getContentPane().add(passwordTextField);
        passwordTextField.setBounds(310, 130, 100, 19);

        ezTitleLabel.setFont(new java.awt.Font("Mongolian Baiti", 0, 48)); // NOI18N
        ezTitleLabel.setForeground(new java.awt.Color(0, 102, 51));
        ezTitleLabel.setText("EZ Shopping");
        getContentPane().add(ezTitleLabel);
        ezTitleLabel.setBounds(170, 30, 290, 50);

        loginButton.setForeground(new java.awt.Color(0, 0, 0));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(310, 170, 100, 25);

        forgotPasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        forgotPasswordLabel.setText("Forgot Password");
        forgotPasswordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPasswordLabelMouseClicked(evt);
            }
        });
        getContentPane().add(forgotPasswordLabel);
        forgotPasswordLabel.setBounds(310, 210, 110, 15);

        backgroundjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ez/imgs/background_color.jpg"))); // NOI18N
        getContentPane().add(backgroundjLabel);
        backgroundjLabel.setBounds(0, 0, 630, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forgotPasswordLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordLabelMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_forgotPasswordLabelMouseClicked

    /**
     * loginButtonActionPerformed
     *
     * @dexcription on click takes user name and password and provides them to
     * the login class for the user to login
     */
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
          
        String userN = userNameTextField.getText();
        String pwd = passwordTextField.getText();

        Logger log = Logger.getInstance();
        String loginResult = log.login(userN, pwd);
        
        if (loginResult.contains("successfully")) {
            
            loggedIn = true;
            loginResult += ". You can close this Window now";
            JOptionPane.showMessageDialog(null, loginResult);   
            
        } else {
            loggedIn = false;
            JOptionPane.showMessageDialog(null, loginResult);
        }
    }//GEN-LAST:event_loginButtonActionPerformed
 
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundjLabel;
    private javax.swing.JLabel ezTitleLabel;
    private javax.swing.JLabel forgotPasswordLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
