/*
 * 
 */
package ez;

/**
 *
 * @author DiegoArboleda
 */
public class EZ_GUI extends javax.swing.JFrame {

    /**
     * Creates new form EZ_GUI
     */
    public EZ_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        ezTitleLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        backgroundjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(660, 629));
        getContentPane().setLayout(null);

        usernameLabel.setBackground(new java.awt.Color(255, 255, 255));
        usernameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(0, 0, 0));
        usernameLabel.setText("User Name:");
        getContentPane().add(usernameLabel);
        usernameLabel.setBounds(200, 100, 80, 19);

        passwordLabel.setBackground(new java.awt.Color(255, 255, 255));
        passwordLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(0, 0, 0));
        passwordLabel.setText("Password:");
        passwordLabel.setToolTipText("");
        getContentPane().add(passwordLabel);
        passwordLabel.setBounds(200, 130, 72, 19);
        getContentPane().add(userNameTextField);
        userNameTextField.setBounds(310, 100, 100, 19);
        getContentPane().add(passwordTextField);
        passwordTextField.setBounds(310, 130, 100, 19);

        ezTitleLabel.setFont(new java.awt.Font("Mongolian Baiti", 0, 48)); // NOI18N
        ezTitleLabel.setForeground(new java.awt.Color(0, 102, 51));
        ezTitleLabel.setText("EZ Shopping");
        getContentPane().add(ezTitleLabel);
        ezTitleLabel.setBounds(170, 30, 290, 50);

        loginButton.setForeground(new java.awt.Color(0, 0, 0));
        loginButton.setText("Login");
        getContentPane().add(loginButton);
        loginButton.setBounds(310, 170, 100, 25);

        backgroundjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ez/imgs/background_color.jpg"))); // NOI18N
        getContentPane().add(backgroundjLabel);
        backgroundjLabel.setBounds(0, 0, 630, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EZ_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EZ_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EZ_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EZ_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EZ_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundjLabel;
    private javax.swing.JLabel ezTitleLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
